### ISSUE TITLE
error message upon entering site

### ISSUE THREAD

**Issue by rcrath** [amaclean199/soundscape-generator#6]
Able to get welcom screen after workaround in issue #5 but upon entering the "soundsscape" portion I get a bunch of file not found messages:

```
rich[scripts]$ cd ..
(.venv) rich[soundscape-generator]$ python src/application.py --port 8000 --debug
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 319-325-887
127.0.0.1 - - [22/Mar/2020 17:09:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2020 17:09:20] "GET /soundscapes HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rich/bin/soundscape-generator/.venv/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rich/bin/soundscape-generator/src/application.py", line 209, in show_index
    return make_response(open(os.path.join(DIR,
FileNotFoundError: [Errno 2] No such file or directory: '/home/rich/bin/soundscape-generator/src/frontend/build/index.html'
127.0.0.1 - - [22/Mar/2020 17:09:20] "GET /soundscapes?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2020 17:09:20] "GET /soundscapes?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2020 17:09:20] "GET /soundscapes?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2020 17:09:21] "GET /soundscapes?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by amaclean199** [comment]
Hi thanks for letting us know about this too. I have updated the README with more detailed instructions in 919300f805f534d184dae26ddd28626fc8e652ed.
